Run eval with vertex instead of Gemini
The post-deploy jobs are broken due to lack of credentails to vertexAI.
Error: /opt/app-root/src/test/prow/entrypoint.sh: line 24: GOOGLE_APPLICATION_CREDENTIALS: unbound variable
This was the auto promotion from integration to stage